<form
    action="<?=APP::config('url') ?>review/novo" 
    method="POST">

    <label>Comment
        <input type="text" name="comment" 
        value="<?=$review['comment']?>" />
    </label>

    <label>Grade
        <input type="number" name="grade" 
        value="<?=$review['grade']?>" />
    </label>

    <label>Posted date
        <input type="date" name="posted_date" 
        value="<?=$review['posted_date']?>" />
    </label>

    <p>
        <?=$poruka ?>
    </p>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
        <a class="button expanded alert" 
        href="<?=APP::config('url') ?>review/index">
            Cancel
        </a>    
        </div>
        <div class="large-6 small-12 cell">
            <input type="submit" class="button expanded" 
                value="Add new review"></input>
        </div>
    </div>

</form>