<form
    action="<?=APP::config('url') ?>review/novo" 
    method="POST">
    <label>User
              <select name="users" id="user">
                <option <?php if($review->users==0){
                    echo ' selected="selected" ';
                }?> value="0">Odaberite korisnika</option>
                <?php foreach($users as $user): ?>
                    <option <?php if($review->users==$user->id){
                    echo ' selected="selected" ';
                }?> value="<?=$user->id?>"></option>
                <?php endforeach; ?>
              </select>
            </label>

            <label>Property
              <select name="property" id="property">
                <option <?php if($review->property==0){
                    echo ' selected="selected" ';
                }?> value="0">Odaberite nekretninu</option>
                <?php foreach($properties as $property): ?>
                    <option <?php if($review->properties==$property->id){
                    echo ' selected="selected" ';
                }?> value="<?=$property->id?>"><?=$property->name?></option>
                <?php endforeach; ?>
              </select>
            </label>

    <label>Comment
        <input type="text" name="comment" 
        value="<?=$review->comment?>" />
    </label>

    <label>Grade
        <input type="number" name="grade" 
        value="<?=$review->grade?>" />
    </label>

    <label>Posted date
        <input type="date" name="posted_date" 
        value="<?=$review->posted_date?>" />
    </label>

    <p>
        <?=$poruka ?>
    </p>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
        <a class="button expanded alert" 
        href="<?=APP::config('url') ?>review/index">
            Cancel
        </a>    
        </div>
        <div class="large-6 small-12 cell">
            <input type="submit" class="button expanded" 
                value="Add new review"></input>
        </div>
    </div>

</form>