<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="example-menu"></button>
  <div class="title-bar-title"><?=APP::config('nazivAPP') ?></div>
</div>

<div class="top-bar" id="example-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li>
      <a href="<?=APP::config('url') ?>">
            <?=APP::config('nazivAPP') ?>
        </a>
    </li>

      <li><a href="<?=APP::config('url') ?>index/onama">About us</a></li>
      
      <li><a href="<?=APP::config('url') ?>index/properties">Properites</a></li>

      <?php if(isset($_SESSION['autoriziran'])): ?>
        <!-- ovdje dođe privatni dio izbornika -->
      <?php endif; ?>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li>
          <?php if(!isset($_SESSION['autoriziran'])): ?>
          <a href="<?=APP::config('url') ?>index/login">Login</a>
          <?php else: ?>
            <a href="<?=APP::config('url') ?>index/logout">Logout</a>
          <?php endif; ?>
        
        </li>
    </ul>
  </div>
</div>