<?php 
// najlošije rješenje dovlačenja podataka iz baze je da ovdje se spojimo
// i dovučemo podatke

?>

<a class="button expanded success" href="<?=APP::config('url') ?>property/novo">
    <?php include BP . 'view/predlozak/izgledDodajNovi.phtml' ?>
</a>

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Location</th>
            <th>Number of rooms</th>
            <th>Number of bathrooms</th>
            <th>Total surface</th>
            <th>Year of build</th>
            <th>Condition</th>
            <th>Price</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($property as $property): ?>
            <tr>
                <td><?=$property->name?></td>
                <td><?=$property->location?></td>
                <td><?=$property->room_number?></td>
                <td><?=$property->bathroom_number?></td>
                <td><?=$property->total_surface?></td>
                <td><?=$property->build_year?></td>
                <td><?=$property->condition_?></td>
                <td><?=$property->price?></td>
                <td><?=$property->description?></td>
                <td>
                <a href="<?=APP::config('url') ?>property/promjena?sifra=<?=$property->sifra?>">
                    <?php include BP . 'view/predlozak/izgledPromjeni.phtml' ?>
                </a>
                <a href="<?=APP::config('url') ?>smjer/brisanje?sifra=<?=$property->sifra?>">
                    <?php include BP . 'view/predlozak/izgledObrisi.phtml' ?>
                </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>