<a class="button expanded success" href="<?=APP::config('url') ?>property/novo">
    <?php include BP . 'view/predlozak/izgledDodajNovi.phtml' ?>
</a>

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Location</th>
            <th>Room number</th>
            <th>Bathroom number</th>
            <th>Build year</th>
            <th>Condition</th>
            <th>Price</th>
            <th>Description</th>
            <th>User</th>
            <th>Category</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($entiteti as $entitet): ?>
            <tr>
                <td><?=$entitet->name?></td>
                <td><?=$entitet->location?></td>
                <td><?=$entitet->room_number?></td>
                <td><?=$entitet->bathroom_number?></td>
                <td><?=$entitet->total_surface?></td>
                <td><?=$entitet->build_year?></td>
                <td><?=$entitet->condition_?></td>
                <td><?=$entitet->price?></td>
                <td><?=$entitet->description?></td>
                <td><?=$entitet->users?></td>
                <td><?=$entitet->category?></td>
                <td>
                <a href="<?=APP::config('url') ?>property/promjena?id=<?=$entitet->id?>">
                    <?php include BP . 'view/predlozak/izgledPromjeni.phtml' ?>
                </a>
                <?php if ($entitet->property==0): ?>
                    <a onclick="return confirm('Sigurno obrisati?');"
                    href="<?=APP::config('url') ?>property/brisanje?id=<?=$entitet->id?>">
                        <?php include BP . 'view/predlozak/izgledObrisi.phtml' ?>
                    </a>
                <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>