<form
    action="<?=APP::config('url') ?>property/novo" 
    method="POST">

    <label>Name
        <input type="text" name="name" 
        value="<?=$property['name']?>" />
    </label>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
            <label>Location
                <textarea type="text" name="location" cols="30" 
                rows="5"><?=$property['location']?></textarea>
            </label>
        </div>
        <div class="large-6 small-12 cell">
            <label>Number of rooms
                <input type="number" name="room_number" 
                value="<?=$property['room_number']?>"/>
            </label>
            </div>
            <div class="large-6 small-12 cell">
            <label>Number of bathrooms
                <input type="number" name="bathroom_number" 
                value="<?=$property['bathroom_number']?>"/>
            </label>
            </div>
            <div class="large-6 small-12 cell">
            <label>Total surface
                <input type="text" name="total_surface" 
                value="<?=$property['total_surface']?>"/>
            </label>
            </div>
            <div class="large-6 small-12 cell">
            <label>Year of build
                <input type="number" name="build_year" 
                value="<?=$property['build_year']?>"/>
            </label>
            </div>
            <div class="large-6 small-12 cell">
            <label>Condition
                <input type="text" name="condition_" 
                value="<?=$property['condition_']?>"/>
            </label>
            </div>
            <div class="large-6 small-12 cell">
            <label>Price
                <input type="number" name="price" 
                value="<?=$property['price']?>"/>
            </label>
            </div>
            <div class="large-6 small-12 cell">
            <label>Description
                <input type="text" name="description" 
                value="<?=$property['description']?>"/>
            </label>
            </div>
    </div>

    <p>
        <?=$poruka ?>
    </p>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
        <a class="button expanded alert" 
        href="<?=APP::config('url') ?>property/index">
            Cancel
        </a>    
        </div>
        <div class="large-6 small-12 cell">
            <input type="submit" class="button expanded" 
                value="Add new property"></input>
        </div>
    </div>

</form>