<form
    action="<?=APP::config('url') ?>image/novo" 
    method="POST">

    <label>Image
        <input type="text" name="image_files" 
        value="<?=$image['image_files']?>" />
    </label>

    <p>
        <?=$poruka ?>
    </p>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
        <a class="button expanded alert" 
        href="<?=APP::config('url') ?>image/index">
            Cancel
        </a>    
        </div>
        <div class="large-6 small-12 cell">
            <input type="submit" class="button expanded" 
                value="Add new image"></input>
        </div>
    </div>

</form>