<form
    action="<?=APP::config('url') ?>image/promjena" 
    method="POST">


    <div class="large-6 small-12 cell">
    <label>Image
        <input type="text" name="image_files" 
        value="<?=$image->image_files?>" />
    </label>
    </div>

        

    <input type="hidden" name="id" value="<?=$image->id ?>" />

    <p>
        <?=$poruka ?>
    </p>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
        <a class="button expanded alert" 
        href="<?=APP::config('url') ?>image/index">
            Cancel
        </a>    
        </div>
        <div class="large-6 small-12 cell">
            <input type="submit" class="button expanded" 
                value="Update image"></input>
        </div>
    </div>

</form>