<?php 
// najlošije rješenje dovlačenja podataka iz baze je da ovdje se spojimo
// i dovučemo podatke

?>

<a class="button expanded success" href="<?=APP::config('url') ?>user/novo">
    <?php include BP . 'view/predlozak/izgledDodajNovi.phtml' ?>
</a>

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Surname</th>
            <th>Password</th>
            <th>E-mail</th>
            <th>Phone</th>
            <th>Address</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($users as $user): ?>
            <tr>
                <td><?=$user->name?></td>
                <td><?=$user->surname?></td>
                <td><?=$user->password?></td>
                <td><?=$user->e_mail?></td>
                <td><?=$user->phone?></td>
                <td><?=$user->address?></td>
                <td>
                <a href="<?=APP::config('url') ?>user/promjena?sifra=<?=$user->sifra?>">
                    <?php include BP . 'view/predlozak/izgledPromjeni.phtml' ?>
                </a>
                <?php if ($user->property==0): ?>
                    <a onclick="return confirm('Sigurno obrisati?');"
                    href="<?=APP::config('url') ?>user/brisanje?sifra=<?=$user->sifra?>">
                        <?php include BP . 'view/predlozak/izgledObrisi.phtml' ?>
                    </a>
                <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>