<form
    action="<?=APP::config('url') ?>user/novo" 
    method="POST">

    <label>Name
        <input type="text" name="name" 
        value="<?=$user['name']?>" />
    </label>
    <label>Surname
        <input type="text" name="surname" 
        value="<?=$user['surname']?>" />
    </label>
    <label>Password
        <input type="text" name="password" 
        value="<?=$user['password']?>" />
    </label>
    <label>E-mail
        <input type="email" name="e_mail" 
        value="<?=$user['e_mail']?>" />
    </label>
    <label>Phone
        <input type="number" name="phone" 
        value="<?=$user['phone']?>" />
    </label>
    <label>Address
        <input type="text" name="address" 
        value="<?=$user['address']?>" />
    </label>

    <p>
        <?=$poruka ?>
    </p>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
        <a class="button expanded alert" 
        href="<?=APP::config('url') ?>user/index">
            Cancel
        </a>    
        </div>
        <div class="large-6 small-12 cell">
            <input type="submit" class="button expanded" 
                value="Add new user"></input>
        </div>
    </div>

</form>