<form
    action="<?=APP::config('url') ?>user/promjena" 
    method="POST">


    <div class="large-6 small-12 cell">
    <label>Name
        <input type="text" name="name" 
        value="<?=$user->name?>" />
    </label>
    </div>

        <div class="large-6 small-12 cell">
            <label>Surname
            <input type="text" name="surname" 
                value="<?=$user->surname?>"/>
            </label>
        </div>
        <div class="large-6 small-12 cell">
            <label>Password
                <input type="text" name="password" 
                value="<?=$user->password?>"/>
            </label>
            <label>E-mail
                <input type="text" name="email" 
                value="<?=$user->e_mail?>"/>
            </label>
            <label>Phone
                <input type="number" name="phone" 
                value="<?=$user->phone?>"/>
            </label>
            <label>Address
                <input type="text" name="address" 
                value="<?=$user->address?>"/>
            </label>
        </div>
    </div>

    <input type="hidden" name="id" value="<?=$user->sifra ?>" />

    <p>
        <?=$poruka ?>
    </p>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
        <a class="button expanded alert" 
        href="<?=APP::config('url') ?>user/index">
            Cancel
        </a>    
        </div>
        <div class="large-6 small-12 cell">
            <input type="submit" class="button expanded" 
                value="Update user"></input>
        </div>
    </div>

</form>