<form
    action="<?=APP::config('url') ?>category/promjena" 
    method="POST">


    <div class="large-6 small-12 cell">
    <label>Name
        <input type="text" name="name" 
        value="<?=$category->name?>" />
    </label>
    </div>

        

    <input type="hidden" name="id" value="<?=$category->id ?>" />

    <p>
        <?=$poruka ?>
    </p>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
        <a class="button expanded alert" 
        href="<?=APP::config('url') ?>category/index">
            Cancel
        </a>    
        </div>
        <div class="large-6 small-12 cell">
            <input type="submit" class="button expanded" 
                value="Update category"></input>
        </div>
    </div>

</form>