<div class="grid-x">
<div class="cell large-4 medium-6 medium-offset-3 small-12 large-offset-4 ">

    <h4 class="text-center">Login</h4>
    <form class="log-in-form" 
     action="<?=APP::config('url') ?>index/autorizacija" 
     method="POST">
    
    <label>E-mail:
        <input type="email" name="email" placeholder="ivan@primjer.hr" 
        value="<?=$email ?>">
    </label>
    <label>Password:
        <input type="password" name="lozinka" placeholder="Password">

    <p><input type="submit" class="button expanded" value="Submit"></input></p>

    <?=$poruka ?>
    </form>
    </div>
</div>
